name: Build
on:
  push:
    branches:
    - main
    - "4.3"
    - "3.0"
    paths-ignore:
    - "README.md"
    - "release-notes/*"
  pull_request:
    branches:
    - main
permissions:
  contents: read
jobs:
  build:
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      matrix:
        java_version: ['8', '11', '17', '21', '25']
    env:
      JAVA_OPTS: "-XX:+TieredCompilation -XX:TieredStopAtLevel=1"
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
    - name: Set up JDK
      uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
      with:
        distribution: "temurin"
        java-version: ${{ matrix.java_version }}
        cache: 'maven'
        server-id: central-snapshots
        server-username: CI_DEPLOY_USERNAME
        server-password: CI_DEPLOY_PASSWORD
    - name: Build
      run: ./mvnw -B -q -ff -ntp verify
    - name: Generate code coverage
      if: ${{ github.event_name != 'pull_request' && matrix.java_version == '8' }}
      run: ./mvnw -B -q -ff -ntp test
    - name: Publish code coverage
      if: ${{ github.event_name != 'pull_request' && matrix.java_version == '8' }}
      uses: codecov/codecov-action@e79a6962e0d4c0c17b229090214935d2e33f8354 # v6.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./target/site/jacoco/jacoco.xml
        flags: unittests
