name: Build
on:
  push:
    branches:
    - main
    - "4.3"
    - "3.0"
    paths-ignore:
    - "README.md"
    - "release-notes/*"
  pull_request:
    branches:
    - main
permissions:
  contents: read
jobs:
  build:
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      matrix:
        java_version: ['8', '11', '17', '21', '25']
    env:
      JAVA_OPTS: "-XX:+TieredCompilation -XX:TieredStopAtLevel=1"
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: Set up JDK
      uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5.4.0
      with:
        distribution: "temurin"
        java-version: ${{ matrix.java_version }}
        cache: 'maven'
        server-id: central-snapshots
        server-username: CI_DEPLOY_USERNAME
        server-password: CI_DEPLOY_PASSWORD
    - name: Build
      run: ./mvnw -B -q -ff -ntp verify
    - name: Generate code coverage
      if: ${{ github.event_name != 'pull_request' && matrix.java_version == '8' }}
      run: ./mvnw -B -q -ff -ntp test
    - name: Publish code coverage
      if: ${{ github.event_name != 'pull_request' && matrix.java_version == '8' }}
      uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./target/site/jacoco/jacoco.xml
        flags: unittests
